### ISSUE TITLE
Using Android RetroFix with the Android app in Kotlin Multiplatform Mobile (KMM) results in unresolved issues.

### ISSUE THREAD

**Issue by seanballais** [SgtSilvio/android-retrofix#15] opened 2022-11-23 16:17 UTC
I have attempted to include Android RetroFix into my project being built with KMM. The Android subproject's `build.gradle.kts` without RetroFix looks like the following:

```kotlin
plugins {
    id("com.android.application")
    kotlin("android")
}

android {
    namespace = "com.pixenamic.copyover.android"
    compileSdk = 33
    defaultConfig {
        applicationId = "com.pixenamic.copyover.android"
        minSdk = 23
        targetSdk = 33
        versionCode = 1
        versionName = "1.0"
    }
    buildFeatures {
        compose = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.3.0"
    }
    packagingOptions {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }
}

dependencies {
    implementation(project(":core"))
    implementation("androidx.compose.ui:ui:1.3.1")
    implementation("androidx.compose.ui:ui-tooling:1.3.1")
    implementation("androidx.compose.ui:ui-tooling-preview:1.3.1")
    implementation("androidx.compose.foundation:foundation:1.3.1")
    implementation("androidx.compose.material:material:1.3.1")
    implementation("androidx.activity:activity-compose:1.6.1")
    implementation("com.hivemq:hivemq-mqtt-client:1.3.0")
}
```

To include RetroFix, I have tried adding the following snippet into the subproject:

```kotlin
plugins {
  id("com.github.sgtsilvio.gradle.android-retrofix") version "0.4.1"
}
```

and also:

```kotlin
buildscript {
  repositories {
    maven {
      url = uri("https://plugins.gradle.org/m2/")
    }
  }
  dependencies {
    classpath("gradle.plugin.com.github.sgtsilvio.gradle:android-retrofix:0.4.1")
  }
}

apply(plugin = "com.github.sgtsilvio.gradle.android-retrofix")
```

Whichever snippet I try, I would get the following error:
```
Script compilation errors:

  Line 08:     namespace = "com.pixenamic.copyover.android"
               ^ Unresolved reference: namespace

  Line 09:     compileSdk = 33
               ^ Unresolved reference: compileSdk

  Line 12:         minSdk = 23
                   ^ Unresolved reference: minSdk

  Line 13:         targetSdk = 33
                   ^ Unresolved reference: targetSdk

  Line 17:     buildFeatures {
               ^ Unresolved reference: buildFeatures

  Line 18:         compose = true
                   ^ Unresolved reference: compose

  Line 20:     composeOptions {
               ^ Unresolved reference: composeOptions

  Line 21:         kotlinCompilerExtensionVersion = "1.3.0"
                   ^ Unresolved reference: kotlinCompilerExtensionVersion

  Line 24:         resources {
                   ^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
                       public inline operator fun <T : Any, C : NamedDomainObjectContainer<TypeVariable(T)>> TypeVariable(C).invoke(configuration: Action<NamedDomainObjectContainerScope<TypeVariable(T)>>): TypeVariable(C) defined in org.gradle.kotlin.dsl
                       public operator fun <T> Closure<TypeVariable(T)>.invoke(): TypeVariable(T) defined in org.gradle.kotlin.dsl
                       public operator fun <T> Closure<TypeVariable(T)>.invoke(x: Any?): TypeVariable(T) defined in org.gradle.kotlin.dsl
                       public operator fun <T> Closure<TypeVariable(T)>.invoke(vararg xs: Any?): TypeVariable(T) defined in org.gradle.kotlin.dsl
                       public operator fun <V> Callable<TypeVariable(V)>.invoke(): TypeVariable(V) defined in org.gradle.kotlin.dsl
                       public operator fun <T, R> DeepRecursiveFunction<TypeVariable(T), TypeVariable(R)>.invoke(value: TypeVariable(T)): TypeVariable(R) defined in kotlin
                       public operator fun <T> Action<in TypeVariable(T)>.invoke(target: TypeVariable(T)): Unit defined in org.gradle.kotlin.dsl
                       public operator fun <T> NamedDomainObjectProvider<TypeVariable(T)>.invoke(action: TypeVariable(T).() -> Unit): Unit defined in org.gradle.kotlin.dsl
                       public operator fun ArtifactHandler.invoke(configuration: ArtifactHandlerScope.() -> Unit): Unit defined in org.gradle.kotlin.dsl
                       public operator fun DependencyConstraintHandler.invoke(configuration: DependencyConstraintHandlerScope.() -> Unit): Unit defined in org.gradle.kotlin.dsl
                       public inline operator fun <T> ExtraPropertiesExtension.invoke(initialValueProvider: () -> TypeVariable(T)): InitialValueExtraPropertyDelegateProvider<TypeVariable(T)> defined in org.gradle.kotlin.dsl
                       public operator fun <T> ExtraPropertiesExtension.invoke(initialValue: TypeVariable(T)): InitialValueExtraPropertyDelegateProvider<TypeVariable(T)> defined in org.gradle.kotlin.dsl
                       public operator fun <T> Spec<TypeVariable(T)>.invoke(arg: TypeVariable(T)): Boolean defined in org.gradle.kotlin.dsl
                       public inline operator fun TaskContainer.invoke(configuration: TaskContainerScope.() -> Unit): TaskContainer defined in org.gradle.kotlin.dsl

  Line 25:             excludes += "/META-INF/{AL2.0,LGPL2.1}"
                                ^ Assignment operators ambiguity:
                                    public operator fun <T> Set<String!>.plus(element: String!): Set<String!> defined in kotlin.collections
                                    public inline operator fun <T> MutableCollection<in String>.plusAssign(element: String): Unit defined in kotlin.collections

10 errors
```

Any solution to this would be appreciated. Nevertheless, I am just going to jump my minimum SDK level from API Level 23 to 24.

**Comment by SgtSilvio** [comment] 2023-02-26 23:04
Hi @seanballais 
Sorry for the delayed response.
The issue should be fixed in version 0.4.2 (https://github.com/SgtSilvio/android-retrofix/releases/tag/v0.4.2).
I will close this issue as resolved. Feel free to comment if the issue is not fixed on your side.

**Closed by SgtSilvio** 2023-02-26 23:04 UTC
Labels: bug
